In [141]:
subjects = ["Mathematics", "Science", "English", "Social Studies", "Computer Science", "Physical Education"]
teachers = {
    "Mr. Kumar": ["Mathematics"],
    "Mrs. Sharma": ["Mathematics"],
    "Ms. Gupta": ["Science"],
    "Mr. Singh": ["Science", "Social Studies"],
    "Mrs. Patel": ["English"],
    "Mr. Joshi": ["English", "Social Studies"],
    "Mr. Malhotra": ["Computer Science"],
    "Mr. Chauhan": ["Physical Education"]
}

days_of_week = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
periods_per_day = 6

class_subject_periods = {
    "Class 6A": {"Mathematics": 6, "Science": 6, "English": 6, "Social Studies": 6, "Computer Science": 3, "Physical Education": 3},
    "Class 6B": {"Mathematics": 6, "Science": 6, "English": 6, "Social Studies": 6, "Computer Science": 3, "Physical Education": 3},
    "Class 7A": {"Mathematics": 6, "Science": 6, "English": 6, "Social Studies": 6, "Computer Science": 4, "Physical Education": 2},
    "Class 7B": {"Mathematics": 6, "Science": 6, "English": 6, "Social Studies": 6, "Computer Science": 4, "Physical Education": 2}
}

# I am following the hierarchy -- Weekdays:Period:Class:Subject:Teacher
subject_wise_teacher = {}
for teacher in teachers:
    for subject in teachers[teacher]:
        if subject not in subject_wise_teacher:
            subject_wise_teacher[subject] = []
        subject_wise_teacher[subject].append(teacher)
# subject_wise_teacher

timetable = {day: {p: {} for p in range(1, periods_per_day + 1)} for day in days_of_week}
# timetable

teacher_schedule = {}
for day in days_of_week:
    teacher_schedule[day] = {}
    for p in range(1, periods_per_day + 1):
        teacher_schedule[day][p] = []
teacher_schedule

{'Monday': {1: [], 2: [], 3: [], 4: [], 5: [], 6: []},
 'Tuesday': {1: [], 2: [], 3: [], 4: [], 5: [], 6: []},
 'Wednesday': {1: [], 2: [], 3: [], 4: [], 5: [], 6: []},
 'Thursday': {1: [], 2: [], 3: [], 4: [], 5: [], 6: []},
 'Friday': {1: [], 2: [], 3: [], 4: [], 5: [], 6: []}}

In [142]:
#class: subject: teacher
class_subject = {}
classes = ["Class 6A", "Class 6B", "Class 7A", "Class 7B"]
for cls in classes:
    class_subject[cls] = {}
    for sub in class_subject_periods[cls]:
        class_subject[cls][sub] = class_subject_periods[cls][sub]

class_subject

{'Class 6A': {'Mathematics': 6,
  'Science': 6,
  'English': 6,
  'Social Studies': 6,
  'Computer Science': 3,
  'Physical Education': 3},
 'Class 6B': {'Mathematics': 6,
  'Science': 6,
  'English': 6,
  'Social Studies': 6,
  'Computer Science': 3,
  'Physical Education': 3},
 'Class 7A': {'Mathematics': 6,
  'Science': 6,
  'English': 6,
  'Social Studies': 6,
  'Computer Science': 4,
  'Physical Education': 2},
 'Class 7B': {'Mathematics': 6,
  'Science': 6,
  'English': 6,
  'Social Studies': 6,
  'Computer Science': 4,
  'Physical Education': 2}}

In [143]:
teacher_schedule = {}
for day in days_of_week:
    teacher_schedule[day] = {}
    for p in range(1, periods_per_day + 1):
        teacher_schedule[day][p] = []
teacher_schedule

{'Monday': {1: [], 2: [], 3: [], 4: [], 5: [], 6: []},
 'Tuesday': {1: [], 2: [], 3: [], 4: [], 5: [], 6: []},
 'Wednesday': {1: [], 2: [], 3: [], 4: [], 5: [], 6: []},
 'Thursday': {1: [], 2: [], 3: [], 4: [], 5: [], 6: []},
 'Friday': {1: [], 2: [], 3: [], 4: [], 5: [], 6: []}}

In [144]:
subjects = list(subject_wise_teacher.keys())
for day in days_of_week:
    for period in range(1, periods_per_day + 1):
        cls_list = classes[1:] + classes[:1]
        for cls in cls_list:
            sub_list = subjects[1:] + subjects[:1]
            assigned = False
            for sub in sub_list:
                if class_subject[cls][sub] == 0:
                    continue
                for t in subject_wise_teacher.get(sub, []):
                    if t not in teacher_schedule[day][period]:
                        timetable[day][period][cls] = (sub, t)
                        class_subject[cls][sub] -= 1
                        teacher_schedule[day][period].append(t)
                        assigned = True
                        break
                if assigned:
                    break

In [145]:
timetable

{'Monday': {1: {'Class 6B': ('Science', 'Ms. Gupta'),
   'Class 7A': ('Science', 'Mr. Singh'),
   'Class 7B': ('Social Studies', 'Mr. Joshi'),
   'Class 6A': ('English', 'Mrs. Patel')},
  2: {'Class 6B': ('Science', 'Ms. Gupta'),
   'Class 7A': ('Science', 'Mr. Singh'),
   'Class 7B': ('Social Studies', 'Mr. Joshi'),
   'Class 6A': ('English', 'Mrs. Patel')},
  3: {'Class 6B': ('Science', 'Ms. Gupta'),
   'Class 7A': ('Science', 'Mr. Singh'),
   'Class 7B': ('Social Studies', 'Mr. Joshi'),
   'Class 6A': ('English', 'Mrs. Patel')},
  4: {'Class 6B': ('Science', 'Ms. Gupta'),
   'Class 7A': ('Science', 'Mr. Singh'),
   'Class 7B': ('Social Studies', 'Mr. Joshi'),
   'Class 6A': ('English', 'Mrs. Patel')},
  5: {'Class 6B': ('Science', 'Ms. Gupta'),
   'Class 7A': ('Science', 'Mr. Singh'),
   'Class 7B': ('Social Studies', 'Mr. Joshi'),
   'Class 6A': ('English', 'Mrs. Patel')},
  6: {'Class 6B': ('Science', 'Ms. Gupta'),
   'Class 7A': ('Science', 'Mr. Singh'),
   'Class 7B': ('Social Studies', 'Mr. Joshi'),
   'Class 6A': ('English', 'Mrs. Patel')}},
 'Tuesday': {1: {'Class 6B': ('Social Studies', 'Mr. Singh'),
   'Class 7A': ('Social Studies', 'Mr. Joshi'),
   'Class 7B': ('Science', 'Ms. Gupta'),
   'Class 6A': ('Computer Science', 'Mr. Malhotra')},
  2: {'Class 6B': ('Social Studies', 'Mr. Singh'),
   'Class 7A': ('Social Studies', 'Mr. Joshi'),
   'Class 7B': ('Science', 'Ms. Gupta'),
   'Class 6A': ('Computer Science', 'Mr. Malhotra')},
  3: {'Class 6B': ('Social Studies', 'Mr. Singh'),
   'Class 7A': ('Social Studies', 'Mr. Joshi'),
   'Class 7B': ('Science', 'Ms. Gupta'),
   'Class 6A': ('Computer Science', 'Mr. Malhotra')},
  4: {'Class 6B': ('Social Studies', 'Mr. Singh'),
   'Class 7A': ('Social Studies', 'Mr. Joshi'),
   'Class 7B': ('Science', 'Ms. Gupta'),
   'Class 6A': ('Physical Education', 'Mr. Chauhan')},
  5: {'Class 6B': ('Social Studies', 'Mr. Singh'),
   'Class 7A': ('Social Studies', 'Mr. Joshi'),
   'Class 7B': ('Science', 'Ms. Gupta'),
   'Class 6A': ('Physical Education', 'Mr. Chauhan')},
  6: {'Class 6B': ('Social Studies', 'Mr. Singh'),
   'Class 7A': ('Social Studies', 'Mr. Joshi'),
   'Class 7B': ('Science', 'Ms. Gupta'),
   'Class 6A': ('Physical Education', 'Mr. Chauhan')}},
 'Wednesday': {1: {'Class 6B': ('English', 'Mrs. Patel'),
   'Class 7A': ('English', 'Mr. Joshi'),
   'Class 7B': ('Computer Science', 'Mr. Malhotra'),
   'Class 6A': ('Science', 'Ms. Gupta')},
  2: {'Class 6B': ('English', 'Mrs. Patel'),
   'Class 7A': ('English', 'Mr. Joshi'),
   'Class 7B': ('Computer Science', 'Mr. Malhotra'),
   'Class 6A': ('Science', 'Ms. Gupta')},
  3: {'Class 6B': ('English', 'Mrs. Patel'),
   'Class 7A': ('English', 'Mr. Joshi'),
   'Class 7B': ('Computer Science', 'Mr. Malhotra'),
   'Class 6A': ('Science', 'Ms. Gupta')},
  4: {'Class 6B': ('English', 'Mrs. Patel'),
   'Class 7A': ('English', 'Mr. Joshi'),
   'Class 7B': ('Computer Science', 'Mr. Malhotra'),
   'Class 6A': ('Science', 'Ms. Gupta')},
  5: {'Class 6B': ('English', 'Mrs. Patel'),
   'Class 7A': ('English', 'Mr. Joshi'),
   'Class 7B': ('Physical Education', 'Mr. Chauhan'),
   'Class 6A': ('Science', 'Ms. Gupta')},
  6: {'Class 6B': ('English', 'Mrs. Patel'),
   'Class 7A': ('English', 'Mr. Joshi'),
   'Class 7B': ('Physical Education', 'Mr. Chauhan'),
   'Class 6A': ('Science', 'Ms. Gupta')}},
 'Thursday': {1: {'Class 6B': ('Computer Science', 'Mr. Malhotra'),
   'Class 7A': ('Physical Education', 'Mr. Chauhan'),
   'Class 7B': ('English', 'Mrs. Patel'),
   'Class 6A': ('Social Studies', 'Mr. Singh')},
  2: {'Class 6B': ('Computer Science', 'Mr. Malhotra'),
   'Class 7A': ('Physical Education', 'Mr. Chauhan'),
   'Class 7B': ('English', 'Mrs. Patel'),
   'Class 6A': ('Social Studies', 'Mr. Singh')},
  3: {'Class 6B': ('Computer Science', 'Mr. Malhotra'),
   'Class 7A': ('Mathematics', 'Mr. Kumar'),
   'Class 7B': ('English', 'Mrs. Patel'),
   'Class 6A': ('Social Studies', 'Mr. Singh')},
  4: {'Class 6B': ('Physical Education', 'Mr. Chauhan'),
   'Class 7A': ('Computer Science', 'Mr. Malhotra'),
   'Class 7B': ('English', 'Mrs. Patel'),
   'Class 6A': ('Social Studies', 'Mr. Singh')},
  5: {'Class 6B': ('Physical Education', 'Mr. Chauhan'),
   'Class 7A': ('Computer Science', 'Mr. Malhotra'),
   'Class 7B': ('English', 'Mrs. Patel'),
   'Class 6A': ('Social Studies', 'Mr. Singh')},
  6: {'Class 6B': ('Physical Education', 'Mr. Chauhan'),
   'Class 7A': ('Computer Science', 'Mr. Malhotra'),
   'Class 7B': ('English', 'Mrs. Patel'),
   'Class 6A': ('Social Studies', 'Mr. Singh')}},
 'Friday': {1: {'Class 6B': ('Mathematics', 'Mr. Kumar'),
   'Class 7A': ('Computer Science', 'Mr. Malhotra'),
   'Class 7B': ('Mathematics', 'Mrs. Sharma')},
  2: {'Class 6B': ('Mathematics', 'Mr. Kumar'),
   'Class 7A': ('Mathematics', 'Mrs. Sharma')},
  3: {'Class 6B': ('Mathematics', 'Mr. Kumar'),
   'Class 7A': ('Mathematics', 'Mrs. Sharma')},
  4: {'Class 6B': ('Mathematics', 'Mr. Kumar'),
   'Class 7A': ('Mathematics', 'Mrs. Sharma')},
  5: {'Class 6B': ('Mathematics', 'Mr. Kumar'),
   'Class 7A': ('Mathematics', 'Mrs. Sharma')},
  6: {'Class 6B': ('Mathematics', 'Mr. Kumar'),
   'Class 7A': ('Mathematics', 'Mrs. Sharma')}}}

In [129]:
teacher_schedule = {}
class_counter = {}
for day in days_of_week:
    teacher_schedule[day] = {}
    for p in range(1, periods_per_day + 1):
        teacher_schedule[day][p] = []
for cls in classes:
    class_counter[cls] = {}
    for sub in class_subject_periods[cls]:
        class_counter[cls][sub] = 0

for day in timetable:
    for p in timetable[day]:
        seen_teachers = []
        for cls in timetable[day][p]:
            sub, t = timetable[day][p][cls]
            if t in seen_teachers:
                print(False, "Teacher {} double-booked on {} period {}.".format(t, day, p))
            if sub not in teachers[t]:
                print(False, "Teacher {} is not qualified to teach {}.".format(t, sub))
            class_counter[cls][sub] += 1
            seen_teachers.append(t)

for cls in class_subject_periods:
    for sub in class_subject_periods[cls]:
        if class_counter[cls][sub] != class_subject_periods[cls][sub]:
            print(False, "{} has incorrect number of {} classes.".format(cls, sub))

False Class 6A has incorrect number of Mathematics classes.
False Class 7B has incorrect number of Mathematics classes.

In [131]:
subjects = ["Mathematics", "Science", "English", "Social Studies", "Computer Science", "Physical Education"]
teachers = {
    "Mr. Kumar": ["Mathematics"],
    "Mrs. Sharma": ["Mathematics"],
    "Ms. Gupta": ["Science"],
    "Mr. Singh": ["Science", "Social Studies"],
    "Mrs. Patel": ["English"],
    "Mr. Joshi": ["English", "Social Studies"],
    "Mr. Malhotra": ["Computer Science"],
    "Mr. Chauhan": ["Physical Education"]
}

days_of_week = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
periods_per_day = 6

class_subject_periods = {
    "Class 6A": {"Mathematics": 6, "Science": 6, "English": 6, "Social Studies": 6, "Computer Science": 3, "Physical Education": 3},
    "Class 6B": {"Mathematics": 6, "Science": 6, "English": 6, "Social Studies": 6, "Computer Science": 3, "Physical Education": 3},
    "Class 7A": {"Mathematics": 6, "Science": 6, "English": 6, "Social Studies": 6, "Computer Science": 4, "Physical Education": 2},
    "Class 7B": {"Mathematics": 6, "Science": 6, "English": 6, "Social Studies": 6, "Computer Science": 4, "Physical Education": 2}
}

# I am following the hierarchy -- Weekdays:Period:Class:Subject:Teacher
subject_wise_teacher = {}
for teacher in teachers:
    for subject in teachers[teacher]:
        if subject not in subject_wise_teacher:
            subject_wise_teacher[subject] = []
        subject_wise_teacher[subject].append(teacher)
# subject_wise_teacher

timetable = {day: {p: {} for p in range(1, periods_per_day + 1)} for day in days_of_week}
# timetable

teacher_schedule = {}
for day in days_of_week:
    teacher_schedule[day] = {}
    for p in range(1, periods_per_day + 1):
        teacher_schedule[day][p] = []
teacher_schedule

{'Monday': {1: [], 2: [], 3: [], 4: [], 5: [], 6: []},
 'Tuesday': {1: [], 2: [], 3: [], 4: [], 5: [], 6: []},
 'Wednesday': {1: [], 2: [], 3: [], 4: [], 5: [], 6: []},
 'Thursday': {1: [], 2: [], 3: [], 4: [], 5: [], 6: []},
 'Friday': {1: [], 2: [], 3: [], 4: [], 5: [], 6: []}}

In [132]:
#1. Each class needs to study a specific set of subjects.
class_subject = {class_: {"subject","teacher"} for class_ in classes}
class_subject

{'Class 6A': {'subject', 'teacher'},
 'Class 6B': {'subject', 'teacher'},
 'Class 7A': {'subject', 'teacher'},
 'Class 7B': {'subject', 'teacher'}}

In [133]:
flat_class_subject_dict = {
    f"{cls}-{subject}": count
    for cls, subjects in class_subject_periods.items()
    for subject, count in subjects.items()
}

In [134]:
flat_class_subject_dict

{'Class 6A-Mathematics': 6,
 'Class 6A-Science': 6,
 'Class 6A-English': 6,
 'Class 6A-Social Studies': 6,
 'Class 6A-Computer Science': 3,
 'Class 6A-Physical Education': 3,
 'Class 6B-Mathematics': 6,
 'Class 6B-Science': 6,
 'Class 6B-English': 6,
 'Class 6B-Social Studies': 6,
 'Class 6B-Computer Science': 3,
 'Class 6B-Physical Education': 3,
 'Class 7A-Mathematics': 6,
 'Class 7A-Science': 6,
 'Class 7A-English': 6,
 'Class 7A-Social Studies': 6,
 'Class 7A-Computer Science': 4,
 'Class 7A-Physical Education': 2,
 'Class 7B-Mathematics': 6,
 'Class 7B-Science': 6,
 'Class 7B-English': 6,
 'Class 7B-Social Studies': 6,
 'Class 7B-Computer Science': 4,
 'Class 7B-Physical Education': 2}

In [ ]:
schedule_output
for day, period_map in schedule.items():
    for a,b in period_map.items():
        for i in b:
            print({i[0]:(i[1],i[2])})

# {
#     day: {
#         period: val for period, val in period_map.items()
#     } for day, period_map in schedule.items()
# }

{'Class 6B': {'Mr. Chauhan', 'Physical Education'}}
{'Class 6A': {'Social Studies', 'Mr. Singh'}}
{'Class 7A': {'Mr. Kumar', 'Mathematics'}}
{'Class 7B': {'Mathematics', 'Mrs. Sharma'}}
{'Class 7B': {'Science', 'Mr. Singh'}}
{'Class 7A': {'Computer Science', 'Mr. Malhotra'}}
{'Class 6A': {'Science', 'Ms. Gupta'}}
{'Class 6B': {'Mrs. Patel', 'English'}}
{'Class 7A': {'Mr. Joshi', 'English'}}
{'Class 6A': {'Mathematics', 'Mrs. Sharma'}}
{'Class 7B': {'Mr. Chauhan', 'Physical Education'}}
{'Class 6B': {'Mr. Kumar', 'Mathematics'}}
{'Class 7B': {'Mr. Chauhan', 'Physical Education'}}
{'Class 6B': {'Mrs. Patel', 'English'}}
{'Class 7A': {'Social Studies', 'Mr. Singh'}}
{'Class 6A': {'Mr. Joshi', 'Social Studies'}}
{'Class 6B': {'Mr. Chauhan', 'Physical Education'}}
{'Class 7B': {'Mr. Joshi', 'Social Studies'}}
{'Class 6A': {'Social Studies', 'Mr. Singh'}}
{'Class 7A': {'Mrs. Patel', 'English'}}
{'Class 7B': {'Mr. Joshi', 'Social Studies'}}
{'Class 7A': {'Social Studies', 'Mr. Singh'}}
{'Class 6B': {'Science', 'Ms. Gupta'}}
{'Class 6A': {'Mr. Chauhan', 'Physical Education'}}
{'Class 6B': {'Computer Science', 'Mr. Malhotra'}}
{'Class 6A': {'Social Studies', 'Mr. Singh'}}
{'Class 7B': {'Mr. Kumar', 'Mathematics'}}
{'Class 7A': {'Mrs. Patel', 'English'}}
{'Class 6A': {'Science', 'Mr. Singh'}}
{'Class 6B': {'Computer Science', 'Mr. Malhotra'}}
{'Class 7A': {'Mathematics', 'Mrs. Sharma'}}
{'Class 7B': {'Mr. Kumar', 'Mathematics'}}
{'Class 6B': {'Mathematics', 'Mrs. Sharma'}}
{'Class 7A': {'Science', 'Ms. Gupta'}}
{'Class 6A': {'Mr. Chauhan', 'Physical Education'}}
{'Class 7B': {'Mr. Joshi', 'Social Studies'}}
{'Class 6B': {'Mathematics', 'Mrs. Sharma'}}
{'Class 7A': {'Mrs. Patel', 'English'}}
{'Class 6A': {'Science', 'Mr. Singh'}}
{'Class 7B': {'Mr. Joshi', 'English'}}
{'Class 7A': {'Mathematics', 'Mrs. Sharma'}}
{'Class 6B': {'Mr. Chauhan', 'Physical Education'}}
{'Class 6A': {'Social Studies', 'Mr. Singh'}}
{'Class 7B': {'Science', 'Ms. Gupta'}}
{'Class 6A': {'Science', 'Mr. Singh'}}
{'Class 7B': {'Science', 'Ms. Gupta'}}
{'Class 6B': {'Mr. Joshi', 'English'}}
{'Class 7A': {'Mr. Chauhan', 'Physical Education'}}
{'Class 6A': {'Mr. Joshi', 'Social Studies'}}
{'Class 7A': {'Social Studies', 'Mr. Singh'}}
{'Class 6B': {'Computer Science', 'Mr. Malhotra'}}
{'Class 7B': {'Mrs. Patel', 'English'}}
{'Class 6A': {'Mr. Chauhan', 'Physical Education'}}
{'Class 7B': {'Mrs. Patel', 'English'}}
{'Class 6B': {'Science', 'Ms. Gupta'}}
{'Class 7A': {'Mathematics', 'Mrs. Sharma'}}
{'Class 7A': {'Science', 'Ms. Gupta'}}
{'Class 6B': {'Mrs. Patel', 'English'}}
{'Class 6A': {'Mr. Joshi', 'English'}}
{'Class 7B': {'Science', 'Mr. Singh'}}
{'Class 7A': {'Mr. Joshi', 'Social Studies'}}
{'Class 7B': {'Mrs. Patel', 'English'}}
{'Class 6A': {'Mathematics', 'Mrs. Sharma'}}
{'Class 6B': {'Social Studies', 'Mr. Singh'}}
{'Class 6B': {'Mr. Kumar', 'Mathematics'}}
{'Class 7B': {'Science', 'Ms. Gupta'}}
{'Class 7A': {'Mr. Joshi', 'Social Studies'}}
{'Class 6A': {'Mathematics', 'Mrs. Sharma'}}
{'Class 7A': {'Computer Science', 'Mr. Malhotra'}}
{'Class 7B': {'Social Studies', 'Mr. Singh'}}
{'Class 6B': {'Mr. Joshi', 'English'}}
{'Class 6A': {'Mathematics', 'Mrs. Sharma'}}
{'Class 7A': {'Mr. Joshi', 'English'}}
{'Class 6B': {'Mathematics', 'Mrs. Sharma'}}
{'Class 7B': {'Mr. Kumar', 'Mathematics'}}
{'Class 6A': {'Computer Science', 'Mr. Malhotra'}}
{'Class 7A': {'Social Studies', 'Mr. Singh'}}
{'Class 6A': {'Mrs. Patel', 'English'}}
{'Class 7B': {'Computer Science', 'Mr. Malhotra'}}
{'Class 6B': {'Mr. Joshi', 'Social Studies'}}
{'Class 6A': {'Science', 'Mr. Singh'}}
{'Class 6B': {'Mrs. Patel', 'English'}}
{'Class 7A': {'Computer Science', 'Mr. Malhotra'}}
{'Class 7B': {'Mr. Kumar', 'Mathematics'}}
{'Class 7A': {'Science', 'Ms. Gupta'}}
{'Class 6B': {'Science', 'Mr. Singh'}}
{'Class 7B': {'Mr. Joshi', 'Social Studies'}}
{'Class 6A': {'Mrs. Patel', 'English'}}
{'Class 6A': {'Mrs. Patel', 'English'}}
{'Class 7B': {'Science', 'Ms. Gupta'}}
{'Class 7A': {'Mr. Joshi', 'English'}}
{'Class 6B': {'Mr. Kumar', 'Mathematics'}}
{'Class 7A': {'Computer Science', 'Mr. Malhotra'}}
{'Class 7B': {'Mr. Kumar', 'Mathematics'}}
{'Class 6A': {'Mathematics', 'Mrs. Sharma'}}
{'Class 6B': {'Mr. Joshi', 'Social Studies'}}
{'Class 7B': {'Mrs. Patel', 'English'}}
{'Class 6A': {'Computer Science', 'Mr. Malhotra'}}
{'Class 7A': {'Science', 'Ms. Gupta'}}
{'Class 6B': {'Science', 'Mr. Singh'}}
{'Class 7B': {'Mrs. Patel', 'English'}}
{'Class 6A': {'Science', 'Mr. Singh'}}
{'Class 6B': {'Mr. Joshi', 'Social Studies'}}
{'Class 7A': {'Mathematics', 'Mrs. Sharma'}}
{'Class 7A': {'Mr. Chauhan', 'Physical Education'}}
{'Class 6A': {'Computer Science', 'Mr. Malhotra'}}
{'Class 6B': {'Social Studies', 'Mr. Singh'}}
{'Class 7B': {'Mr. Joshi', 'Social Studies'}}
{'Class 7A': {'Mathematics', 'Mrs. Sharma'}}
{'Class 6B': {'Social Studies', 'Mr. Singh'}}
{'Class 7B': {'Computer Science', 'Mr. Malhotra'}}
{'Class 6A': {'Mrs. Patel', 'English'}}
{'Class 7A': {'Science', 'Mr. Singh'}}
{'Class 7B': {'Computer Science', 'Mr. Malhotra'}}
{'Class 6A': {'Mr. Joshi', 'English'}}
{'Class 6B': {'Science', 'Ms. Gupta'}}
{'Class 6B': {'Science', 'Ms. Gupta'}}
{'Class 7A': {'Science', 'Mr. Singh'}}
{'Class 7B': {'Computer Science', 'Mr. Malhotra'}}
{'Class 6A': {'Mathematics', 'Mrs. Sharma'}}

In [ ]:
from collections import defaultdict
import random

# Data
subjects = ["Mathematics", "Science", "English", "Social Studies", "Computer Science", "Physical Education"]
teachers = {
    "Mr. Kumar": ["Mathematics"],
    "Mrs. Sharma": ["Mathematics"],
    "Ms. Gupta": ["Science"],
    "Mr. Singh": ["Science", "Social Studies"],
    "Mrs. Patel": ["English"],
    "Mr. Joshi": ["English", "Social Studies"],
    "Mr. Malhotra": ["Computer Science"],
    "Mr. Chauhan": ["Physical Education"]
}

days_of_week = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
periods_per_day = 6

class_subject_periods = {
    "Class 6A": {"Mathematics": 6, "Science": 6, "English": 6, "Social Studies": 6, "Computer Science": 3, "Physical Education": 3},
    "Class 6B": {"Mathematics": 6, "Science": 6, "English": 6, "Social Studies": 6, "Computer Science": 3, "Physical Education": 3},
    "Class 7A": {"Mathematics": 6, "Science": 6, "English": 6, "Social Studies": 6, "Computer Science": 4, "Physical Education": 2},
    "Class 7B": {"Mathematics": 6, "Science": 6, "English": 6, "Social Studies": 6, "Computer Science": 4, "Physical Education": 2}
}


class_subject_periods_remaining = {
    f"{cls}-{subj}": count
    for cls, subj_map in class_subject_periods.items()
    for subj, count in subj_map.items()
}


subject_teachers = defaultdict(list)
for teacher, subs in teachers.items():
    for subj in subs:
        subject_teachers[subj].append(teacher)


availability = {
    (day, period): set(teachers.keys())
    for day in days_of_week
    for period in range(1, periods_per_day + 1)
}


schedule = defaultdict(lambda: defaultdict(list))


def get_available_class_subjects():
    return [k for k, v in class_subject_periods_remaining.items() if v > 0]


for day in days_of_week:
    for period in range(1, periods_per_day + 1):
        used_teachers = set()
        used_classes = set() 
        class_subjects_today = get_available_class_subjects()
        random.shuffle(class_subjects_today) 
        for cs in class_subjects_today:
            class_name, subject = cs.split("-")
            if class_subject_periods_remaining[cs] <= 0:
                continue
            if class_name in used_classes: 
                continue
            
            possible_teachers = [t for t in subject_teachers[subject]
                                 if t in availability[(day, period)] and t not in used_teachers]
            if possible_teachers:
                teacher = random.choice(possible_teachers)
                
                schedule[day][period].append((class_name, subject, teacher))
                class_subject_periods_remaining[cs] -= 1
                used_teachers.add(teacher)
                used_classes.add(class_name)  
                availability[(day, period)].remove(teacher)


timetable = {
    day: {
        period: {
            class_name: (subject, teacher)
            for (class_name, subject, teacher) in class_list
        }
        for period, class_list in period_map.items()
    }
    for day, period_map in schedule.items()
}


for class_name, (subject, teacher) in timetable["Monday"][1].items():
    print(f"{class_name}: {subject} - {teacher}")

Class 6A: Computer Science - Mr. Malhotra
Class 6B: Physical Education - Mr. Chauhan
Class 7A: Social Studies - Mr. Joshi
Class 7B: Mathematics - Mrs. Sharma

In [ ]:
timetable

In [165]:
teacher_schedule = {}
class_counter = {}
for day in days_of_week:
    teacher_schedule[day] = {}
    for p in range(1, periods_per_day + 1):
        teacher_schedule[day][p] = []
for cls in classes:
    class_counter[cls] = {}
    for sub in class_subject_periods[cls]:
        class_counter[cls][sub] = 0

for day in timetable:
    for p in timetable[day]:
        seen_teachers = []
        for cls in timetable[day][p]:
            sub, t = timetable[day][p][cls]
            if t in seen_teachers:
                print(False, "Teacher {} double-booked on {} period {}.".format(t, day, p))
            if sub not in teachers[t]:
                print(False, "Teacher {} is not qualified to teach {}.".format(t, sub))
            class_counter[cls][sub] += 1
            seen_teachers.append(t)

for cls in class_subject_periods:
    for sub in class_subject_periods[cls]:
        if class_counter[cls][sub] != class_subject_periods[cls][sub]:
            print(False, "{} has incorrect number of {} classes.".format(cls, sub))

False Class 6A has incorrect number of English classes.
False Class 7B has incorrect number of English classes.

In [ ]:
{'Monday': {1: {'Class 6B': ('Science', 'Ms. Gupta'),
   'Class 7A': ('Science', 'Mr. Singh'),
   'Class 7B': ('Social Studies', 'Mr. Joshi'),
   'Class 6A': ('English', 'Mrs. Patel')},
  2: {'Class 6B': ('Science', 'Ms. Gupta'),
   'Class 7A': ('Science', 'Mr. Singh'),
   'Class 7B': ('Social Studies', 'Mr. Joshi'),
   'Class 6A': ('English', 'Mrs. Patel')}}}


{'Monday': {1: [('Class 6B', 'Physical Education', 'Mr. Chauhan'),
   ('Class 6A', 'Social Studies', 'Mr. Singh'),
   ('Class 7A', 'Mathematics', 'Mr. Kumar'),
   ('Class 7B', 'Mathematics', 'Mrs. Sharma')],
  2: [('Class 7B', 'Science', 'Mr. Singh'),
   ('Class 7A', 'Computer Science', 'Mr. Malhotra'),
   ('Class 6A', 'Science', 'Ms. Gupta'),
   ('Class 6B', 'English', 'Mrs. Patel')]}}